# Generated by Django 4.2.6 on 2024-05-22 04:31

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptuerBrand',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='res_app.master')),
                ('brandname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Computer Brands',
            },
            bases=('res_app.master',),
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='res_app.master')),
                ('nameofcourse', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Computer Brands',
            },
            bases=('res_app.master',),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='res_app.master')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('branch_code', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('district_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state_name', chained_model_field='state', limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.district')),
                ('state_name', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.state')),
            ],
            options={
                'verbose_name_plural': 'Branch',
            },
            bases=('res_app.master',),
        ),
    ]
