# Generated by Django 4.2.6 on 2024-05-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0002_comptuerbrand_coursename_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursename',
            options={'verbose_name_plural': 'Course Name'},
        ),
    ]
