# Generated by Django 4.2.6 on 2024-05-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('res_app', '0003_alter_coursename_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTeamBatch',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='res_app.master')),
                ('batch_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=7)),
                ('branch_name', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.branch')),
                ('nameofcourse', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.coursename')),
                ('trainer_name', models.ForeignKey(limit_choices_to={'groups_name': 'Trainer', 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
            bases=('res_app.master',),
        ),
    ]
