# Generated by Django 4.2.6 on 2024-05-23 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('res_app', '0004_oneteambatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneteambatch',
            name='course_type',
        ),
        migrations.AddField(
            model_name='oneteambatch',
            name='batch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oneteambatch',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='oneteambatch',
            name='trainer_name',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Trainer', 'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer'),
        ),
    ]
