# Generated by Django 4.2.6 on 2024-05-26 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0007_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='res_app.master')),
                ('room_name', models.CharField(max_length=100)),
                ('floor', models.CharField(choices=[('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor')], max_length=10)),
                ('room_type', models.CharField(choices=[('conference', 'Conference Room'), ('classroom', 'Class Room')], max_length=10)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('branch_name', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.branch')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
            bases=('res_app.master',),
        ),
    ]
