# Generated by Django 4.2.6 on 2024-05-26 05:40

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0008_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='res_app.master')),
                ('already_allocated', models.BooleanField(default=False)),
                ('reservation_time', models.CharField(choices=[('class', 'Class'), ('meeting', 'Meeting')], max_length=7)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('class', 'Class'), ('project', 'Project'), ('interview', 'Interview')], max_length=10)),
                ('batch_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='branch_name', chained_model_field='branch', limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.oneteambatch')),
                ('branch_name', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.branch')),
                ('room_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='branch_name', chained_model_field='Branch', limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.room')),
            ],
            options={
                'verbose_name_plural': 'Room Allocations',
            },
            bases=('res_app.master',),
        ),
    ]
