# Generated by Django 4.2.6 on 2024-05-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0009_roomallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneteambatch',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='oneteambatch',
            name='batch_name',
        ),
    ]
