# Generated by Django 4.2.6 on 2024-05-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0011_oneteambatch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneteambatch',
            name='batch_name',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
