# Generated by Django 4.2.6 on 2024-05-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0012_alter_oneteambatch_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneteambatch',
            name='start_year',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
