# Generated by Django 4.2.6 on 2024-05-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0013_oneteambatch_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneteambatch',
            name='start_year',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
