# Generated by Django 4.2.6 on 2024-05-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0014_alter_oneteambatch_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='batch_name',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.oneteambatch'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='room_name',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='res_app.room'),
        ),
    ]
